import Navbar from "@/components/layout/Navbar";
import Disclaimer from "@/components/layout/Disclaimer";
import { ShieldCheck, Copyright, FileText } from "lucide-react";

export default function Legal() {
  const year = new Date().getFullYear();

  return (
    <div className="min-h-[100dvh] flex flex-col bg-background">
      <Navbar />

      <main className="flex-1 container mx-auto px-4 py-12 max-w-3xl space-y-16">

        {/* NDA */}
        <section className="space-y-4">
          <div className="flex items-center gap-2 border-b border-border pb-3">
            <ShieldCheck className="w-5 h-5 text-muted-foreground" />
            <h2 className="font-serif text-2xl font-medium">Confidentiality & Non-Disclosure</h2>
          </div>
          <p className="text-sm text-muted-foreground leading-relaxed">
            By accessing CaseLight, you agree that all case data, documents, findings, analyses, 
            simulations, and outputs generated through this platform are strictly confidential. 
            This information is intended solely for the authorized user and the individual(s) 
            on whose behalf it was prepared.
          </p>
          <p className="text-sm text-muted-foreground leading-relaxed">
            You may not share, distribute, publish, sell, or disclose any case materials, 
            findings, or platform outputs to any third party without the express written 
            consent of Lagerman Advocates and the authorized case holder. Unauthorized 
            disclosure may constitute a violation of attorney work-product protections, 
            applicable privacy laws, and this agreement.
          </p>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Case data uploaded to CaseLight is used solely to generate analysis for that case. 
            It is not sold, shared, or used for any other purpose. You are responsible for 
            ensuring you have the legal right to upload any documents you submit for analysis.
          </p>
          <p className="text-sm font-medium text-foreground">
            If you are not the intended recipient of this platform — close it. You are in the wrong place.
          </p>
        </section>

        {/* Copyright */}
        <section className="space-y-4">
          <div className="flex items-center gap-2 border-b border-border pb-3">
            <Copyright className="w-5 h-5 text-muted-foreground" />
            <h2 className="font-serif text-2xl font-medium">Copyright & Intellectual Property</h2>
          </div>
          <p className="text-sm text-muted-foreground leading-relaxed">
            CaseLight — including its name, design, interface, architecture, analytical framework, 
            prompting methodology, court simulation engine, and all associated content — is the 
            original intellectual property of Christy Jo Meade, operating as Lagerman Advocates. 
            All rights reserved. © {year} Lagerman Advocates.
          </p>
          <p className="text-sm text-muted-foreground leading-relaxed">
            No portion of this platform may be copied, reproduced, reverse-engineered, repackaged, 
            resold, or used to build a competing product without express written permission. 
            This includes the platform's analytical logic, prompt structure, output format, 
            and legal categorization system.
          </p>
          <p className="text-sm text-muted-foreground leading-relaxed">
            The concept, framework, and invention of CaseLight originated with a human creator. 
            Any AI-assisted elements of development do not transfer ownership or diminish the 
            intellectual property rights of the original author.
          </p>
          <p className="text-sm font-medium text-foreground">
            Don't think about it. Don't try it. It's covered.
          </p>
        </section>

        {/* Terms of Use */}
        <section className="space-y-4">
          <div className="flex items-center gap-2 border-b border-border pb-3">
            <FileText className="w-5 h-5 text-muted-foreground" />
            <h2 className="font-serif text-2xl font-medium">Terms of Use</h2>
          </div>
          <p className="text-sm text-muted-foreground leading-relaxed">
            CaseLight is a legal document analysis tool designed to assist advocates, 
            incarcerated individuals, and legal professionals in identifying potential 
            constitutional violations, procedural errors, and post-conviction claims 
            within court records.
          </p>
          <p className="text-sm text-muted-foreground leading-relaxed">
            CaseLight does not provide legal advice. It does not establish an attorney-client 
            relationship. It does not guarantee any legal outcome. Analysis generated by 
            CaseLight is a starting point for legal research — not a substitute for a 
            licensed attorney. All findings should be independently verified before use in 
            any legal proceeding.
          </p>
          <p className="text-sm text-muted-foreground leading-relaxed">
            CaseLight is here to tell the truth, not give false hope. The platform will 
            surface what the record contains. What you do with it is up to you.
          </p>
          <p className="text-sm text-muted-foreground leading-relaxed">
            By using this platform you agree to these terms in full. Misuse of this platform — 
            including uploading fraudulent documents, attempting to access another user's data, 
            or using outputs to harm the individuals whose cases are analyzed — is strictly 
            prohibited and may result in permanent revocation of access.
          </p>
          <p className="text-sm font-medium text-foreground">
            Use this tool to find the truth. That's what it's here for.
          </p>
        </section>

      </main>

      <Disclaimer />
    </div>
  );
}
